# (c) Copyright IBM Corp. 2016.  All Rights Reserved.
# Distributed under the terms of the Modified BSD License.

version: "2"

services:
  notebook:
    build: .
    image: zos-spark/scala-notebook
    container_name: ${WORKBOOK_NAME}
    command: >
      start-notebook.sh
      --port=${WORKBOOK_PORT}
    network_mode: "host"
    environment:
      JDBC_USER:
      JDBC_PASS:
      JDBC_HOST:
      MONGO_USER:
      MONGO_PASS:
      MONGO_HOST:
      IBM_JAVA_OPTIONS: "-Dlog4j.configurationFile=/home/jovyan/work/log4j.properties"
    volumes:
      - "work:/home/jovyan/work"
volumes:
  work:
